image:
  repository: whitesource/renovate
  tag: 2.6.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

renovate:
  # Additional env vars
  extraEnvVars: []

  # You must accept the WhiteSource Terms of Service to use the image.
  # Please read https://www.whitesourcesoftware.com/terms-of-service/
  # Set this value to 'y' to consent.
  acceptWhiteSourceTos:

  # Set this to the key you received by email.
  # You can request a license key by submitting the form at https://renovate.whitesourcesoftware.com/on-premises/.
  # Please allow up to 24 hours to receive your license key by email.
  licenseKey:

  # Which platform WhiteSource Renovate will connect to. For example "github" or "gitlab"
  renovatePlatform:

  # API endpoint, include trailing slash. Examples: https://api.github.com/, https://gitlab.com/api/v4/
  renovateEndpoint:

  # Personal Access Token for bot account (GitLab only)
  renovateToken:

  #  The GitHub App ID provided when you provisioned the WhiteSource Renovate app. Force string format by quoting value.
  githubAppId:

  # A string representation of the private key provided by GitHub Enterprise when you provisioned WhiteSource Renovate
  githubAppKey:

  # Personal Access Token for github.com (used for retrieving changelogs)
  githubComToken:

  # Optional, defaults to 'renovate'
  webhookSecret:

  # PIP index url to get packages from. Will be mounted as a secret
  pipIndexUrl:

  # Existing secret with secret values with the following keys:
  #   licenseKey:
  #   renovateToken:
  #   githubAppId:
  #   githubAppKey:
  #   githubComToken:
  #   webhookSecret:
  #   pipIndexUrl:
  existingSecret:

  # Optional, defaults to '0 * * * *' (hourly)
  schedulerCron:

  # Self hosted renovate configuration file, will be mounted as a config map
  config: |
    module.exports = {
      // Enter self-hosted configuration options here.
      // https://docs.renovatebot.com/self-hosted-configuration/
    }

  # Npmrc file. Will be mounted as a secret
  npmrc: # |
    # //registry.npmjs.org/:_authToken=xxxxxx

  # Existing secret with npmrc configuration with key:
  #   .npmrc:
  npmrcExistingSecret:

  # Disable NodeJS SSL verify (do not use for production)
  noNodeTlsVerify: false

  # Disable GIT SSL verify (do not use for production)
  noGitTlsVerify: false

  # Set User Agent WhiteSource Renovate will use to query the registries
  # defaults to https://github.com/renovatebot/renovate
  renovateUserAgent:

  # Set log level, defaults to 'info'. Allowed values: fatal, error, warn, info, debug, trace
  logLevel: info

## Cache Persistence Parameters
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
cachePersistence:
  ## Enable persistence using Persistent Volume Claims
  enabled: false
  ## Persistent Volume storage class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
  storageClass: ""
  ## @param Persistent Volume access modes
  accessModes:
    - ReadWriteOnce
  ## Persistent Volume size
  size: 1Gi
  ## The name of an existing PVC to use for persistence
  existingClaim: ""

service:
  type: ClusterIP
  port: 80
  annotations: {}
    # cloud.google.com/load-balancer-type: "Internal"

ingress:
  enabled: false

  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx

  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - whitesource-renovate.local
  tls: []
  #  - secretName: whitesource-renovate-tls
  #    hosts:
  #      - whitesource-renovate.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext: {}

extraVolumes: []
  # - name: secrets-store-inline
  #   csi:
  #     driver: secrets-store.csi.k8s.io
  #     readOnly: true
  #     volumeAttributes:
  #       secretProviderClass: "some-secret-store"

extraVolumeMounts: []
  # - name: secrets-store-inline
  #   mountPath: "/mnt/secrets-store"
  #   readOnly: true
