version: "3.6"
services:
  renovate:
    image: renovate/pro:0.14.0
    restart: on-failure
    environment:
      - ACCEPT_AGREEMENT # You must accept the Renovate User Agreement ot use the image
      - LICENSE_MODE # Set to commercial if you have purchased a license, otherwise it defaults to evaluation
      - LICENSE_NAME # If running in commercial mode, set this to the license name (e.g. company name) as submitted with the Renovate Pro order
      - RENOVATE_PLATFORM=gitlab
      - RENOVATE_ENDPOINT # GitLab endpoint, include trailing slash
      - RENOVATE_TOKEN # Personal Access Token for bot account
      - GITHUB_COM_TOKEN # Personal Access Token for github.com (used for retrieving changelogs)
      - WEBHOOK_SECRET # Optional, default to 'renovate'
      - SCHEDULER_CRON # Optional, defaults to '0 * * * *' (hourly)
    ports:
      - "80:8080" # Receive webhooks on port 80
    volumes:
      - "/tmp/renovate/:/tmp/" # Use a volume for this as the cache will cause a lot of churn
