apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mend-renovate.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.renovateWorker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.renovateWorker.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.renovateWorker.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.renovateWorker.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.renovateWorker.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.renovateWorker.image.repository }}:{{ .Values.renovateWorker.image.tag }}"
          imagePullPolicy: {{ .Values.renovateWorker.image.pullPolicy }}
          env:
            {{- with .Values.renovateWorker.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: MEND_RNV_SERVER_HOSTNAME
              value: "http://{{ include "mend-renovate.fullname" . }}-svc-server"
            {{- if or .Values.renovateServer.mendRnvServerApiSecret .Values.renovateServer.existingSecret }}
            - name: MEND_RNV_SERVER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.server-secret-name" . }}
                  key: mendRnvServerApiSecret
            {{- end }}

            {{- if .Values.license.mendRnvAcceptTos }}
            - name: MEND_RNV_ACCEPT_TOS
              value: {{ .Values.license.mendRnvAcceptTos | quote }}
            {{- end }}
            {{- if or .Values.license.mendRnvLicenseKey .Values.license.existingSecret }}
            - name: MEND_RNV_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.license-secret-name" . }}
                  key: mendRnvLicenseKey
            {{- end }}
            {{- if or .Values.renovateWorker.githubComToken .Values.renovateWorker.existingSecret }}
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.worker-secret-name" . }}
                  key: githubComToken
                  optional: true
            {{- end }}
            {{- if or .Values.renovateWorker.pipIndexUrl .Values.renovateWorker.existingSecret }}
            - name: PIP_INDEX_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.worker-secret-name" . }}
                  key: pipIndexUrl
                  optional: true
            {{- end }}
            {{- if .Values.renovateWorker.mendRnvWorkerExecutionTimeout }}
            - name: MEND_RNV_WORKER_EXECUTION_TIMEOUT
              value: {{ .Values.renovateWorker.mendRnvWorkerExecutionTimeout | quote }}
            {{- end }}
            {{- if .Values.renovateWorker.noNodeTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            {{- end }}
            {{- if .Values.renovateWorker.noGitTlsVerify }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            {{- end }}
            {{- if .Values.renovateWorker.renovateUserAgent }}
            - name: RENOVATE_USER_AGENT
              value: {{ .Values.renovateWorker.renovateUserAgent | quote }}
            {{- end }}
            {{- if .Values.renovateWorker.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.renovateWorker.logLevel | quote }}
            {{- end }}
            {{- if .Values.renovateWorker.logFormat }}
            - name: LOG_FORMAT
              value: {{ .Values.renovateWorker.logFormat | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.renovateWorker.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-js-volume
              mountPath: /usr/src/app/config.js
              subPath: config.js
            {{- if .Values.renovateWorker.npmrc }}
            - name: {{ .Release.Name }}-npmrc-volume
              mountPath: /home/ubuntu/.npmrc
              subPath: .npmrc
            {{- end }}
            - name: {{ .Release.Name }}-cache-volume
              mountPath: /tmp/renovate
          {{- if ne (len .Values.renovateWorker.extraVolumeMounts) 0 }}
            {{ toYaml .Values.renovateWorker.extraVolumeMounts | nindent 12 | trim }}
          {{- end }}
      {{- with .Values.renovateWorker.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- if .Values.renovateWorker.imagePullSecrets }}
      imagePullSecrets:
        - name: .Values.renovateWorker.imagePullSecrets
      {{- end }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-js-volume
          configMap:
            name: {{ .Release.Name }}-config-js
        {{- if or .Values.renovateWorker.npmrc .Values.renovateWorker.npmrcExistingSecret }}
        - name: {{ .Release.Name }}-npmrc-volume
          secret:
            secretName: {{ include "mend-renovate.npmrc-secret-name" . }}
        {{- end }}
        - name: {{ .Release.Name }}-cache-volume
          {{- if .Values.dataPersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.dataPersistence.existingClaim | default (printf "%s-data" (include "mend-renovate.fullname" .)) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
      {{- if ne (len .Values.renovateWorker.extraVolumes) 0 }}
        {{ toYaml .Values.renovateWorker.extraVolumes | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.renovateWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.renovateWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
